const events = [
  {
    id: 1,
    name: 'Sunday cookout',
    host: 'Jake',
    description: 'test description',
    budget: '$300',
    location: 'My house, Austin, Texas',
    cuisine: 'BBQ',
    image: 'https://source.unsplash.com/Fw6nOTesO4c',
    date: '12/12/18',
    time: '12:00pm',
    guests: '12',
    food: false,
    requests: 'NA',
  },
  {
    id: 2,
    name: '10 year anniversary',
    host: 'Rick',
    description: 'test description',
    budget: '$500',
    location: 'My house, Austin, Texas',
    cuisine: 'italian',
    image: 'https://source.unsplash.com/Fw6nOTesO4c',
    date: '12/12/18',
    time: '12:00pm',
    guests: '2',
    food: false,
    requests: 'NA',
  },
  {
    id: 3,
    name: 'Family visiting',
    host: 'Jason',
    description: 'test description',
    budget: '$200',
    location: 'My house, Austin, Texas',
    cuisine: 'Thai',
    image: 'https://source.unsplash.com/Fw6nOTesO4c',
    date: '12/12/18',
    time: '12:00pm',
    guests: '5',
    food: false,
    requests: 'NA',
  },
];

const chefs = [
  {
    id: 1,
    name: 'Jake',
    specialty: 'italian',
    rating: '4.4',
    bio: 'I lived and cooked in Italy for 10 years',
    menu: ['Pasta', 'Pizza', 'Whatever'],
    rate: '$50-100/hr',
    experience: '20+',
    email: 'hotchef1@hotmail.com',
    image: 'https://source.unsplash.com/nvsHAsuFC54',
    street_address: '101 Random Street',
    city_state_zip: 'Austin, Tx, 78741',
    phone: '888-867-5309',
  },
  {
    id: 2,
    name: 'Rick',
    specialty: 'Greek',
    rating: '3.1',
    bio: 'Own and operate a restaurant in NYC',
    menu: ['Pasta', 'Pizza', 'Whatever'],
    rate: '$50-75/hr',
    experience: '10+',
    email: 'hotchef1@hotmail.com',
    image: 'https://source.unsplash.com/nvsHAsuFC54',
  },
  {
    id: 3,
    name: 'Jason',
    specialty: 'Chinese',
    rating: '4.9',
    bio: 'Taught English in China where I learned to cook authenticate chinese food',
    menu: ['Pasta', 'Pizza', 'Whatever'],
    rate: '$24/hr',
    email: 'hotchef1@hotmail.com',
    experience: '7',
    image: 'https://source.unsplash.com/nvsHAsuFC54',
  },
  {
    id: 4,
    name: 'Mark',
    specialty: 'American',
    rating: '3.0',
    bio: 'Grew up with classic southern cooking',
    menu: ['Pasta', 'Pizza', 'Whatever'],
    rate: '$20/hr',
    email: 'hotchef1@hotmail.com',
    experience: '2',
    image: 'https://source.unsplash.com/nvsHAsuFC54',
  },
];

export default {
  events,
  chefs,
};
